name: riptide
description: >-
  Dart port of the Riptide library from Tom Weiland. This port provides functionality for establishing connections with clients and servers using the Riptide protocol.
version: 0.1.7
homepage: https://github.com/JayKay135/Riptide-Dart-Port

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  intl: ^0.19.0
  collection: ^1.18.0

dev_dependencies:
  test: any
  lints: ^3.0.0

topics:
  - network