name: riptide
description: >-
  Dart port of the Riptide library from Tom Weiland. This port provides functionality for establishing connections with clients and servers using the Riptide protocol.
version: 0.0.3
homepage: https://github.com/JayKay135/Riptide-Dart-Port

environment:
  sdk: '^3.0.0'

dependencies:
  intl: ^0.18.1
  collection: ^1.17.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^2.1.1